### ISSUE TITLE
Lambda using wrong file

### ISSUE THREAD

**Issue by agroves333** [jamesridgway/aws-lambda-short-url#1]
Thank you for the great example. I've noticed that [here](https://github.com/jamesridgway/aws-lambda-short-url/blob/master/short_urls.tf#L124) you are using:
`source_code_hash = "${data.archive_file.create_shorturl.output_base64sha256}"`
and I believe it should be:
`source_code_hash = "${data.archive_file.apply_security_headers.output_base64sha256}"`

**Comment by jamesridgway** [comment]
Hi @agroves333 

Thanks for reporting this, you're right, the source code hash should be as you suspect.

I've submitted a fix for this which you can see here:
https://github.com/jamesridgway/aws-lambda-short-url/commit/7540230fd0fede3f6f724915589a7ba64f9e5214

Thanks
