### ISSUE TITLE
Hardcoded S3 IAM policy issue

### ISSUE THREAD

**Issue by yardensachs** [jamesridgway/aws-lambda-short-url#2]
Hi,

Thanks for writing this!

One quick thing I noticed when looking at this:

### This line has the subdomain hardcoded
https://github.com/jamesridgway/aws-lambda-short-url/blob/7540230fd0fede3f6f724915589a7ba64f9e5214/short_urls.tf#L105

### Should change:
```diff
-        "arn:aws:s3:::jmsr.io/*"
+        "arn:aws:s3:::${var.short_url_domain}/*"
```

**Comment by jamesridgway** [comment]
Hi,

Thanks for checking out the project.

Good spot! I've pushed a fix to move that line of the policy over to using the variable.

Let me know if you have any other feedback.

Thanks,
James
